#!/bin/sh
set -e
if [ "$1" = "remove" ] && [ -d /run/systemd/system ]; then
    systemctl stop minsec.service minsec-sync.timer >/dev/null 2>&1 || true
    systemctl disable minsec.service minsec-sync.timer >/dev/null 2>&1 || true
fi
exit 0
